CREATE DATABASE `lt_account_db`;
CREATE DATABASE `lt_archives_db`;
CREATE DATABASE `lt_bbs_db`;
CREATE DATABASE `lt_common_db`;
CREATE DATABASE `lt_consume_db`;
CREATE DATABASE `lt_consume_records_db`;
CREATE DATABASE `lt_partner_db` ;
CREATE DATABASE `lt_purview_db` ;
CREATE DATABASE `lt_weibo_db` ;
CREATE DATABASE `pipi_user_db` ;
CREATE DATABASE `pipi_user_records_db` ;